load("//bazel/java:package.bzl", "java_library")

java_library(
    name = "config",
    testonly = True,
    srcs = ["IndexDefinitionConfigBuilder.java"],
    visibility = ["//visibility:public"],
    exports = ["//src/main/java/com/xgen/mongot/index/definition/config"],
    deps = ["//src/main/java/com/xgen/mongot/index/definition/config"],
)
