load("//bazel/java:package.bzl", "java_library")

java_library(
    name = "options",
    srcs = ["LocalDevOptions.java"],
    visibility = ["//visibility:public"],
    deps = ["@maven//:com_google_guava_guava"],
)
