load("//bazel/java:test.bzl", "java_test_suite")

java_test_suite(
    name = "bson",
    srcs = [
        "BitVectorTest.java",
        "BsonArrayBuilderTest.java",
        "BsonVectorParserTest.java",
        "ByteUtilsTest.java",
        "ByteVectorTest.java",
        "DocumentUtilTest.java",
        "FloatVectorTest.java",
        "JsonCodecTest.java",
        "OptionalCodecTest.java",
        "OptionalPropertyCodecProviderTest.java",
        "ProtoConverterTest.java",
        "VectorTest.java",
        "YamlCodecTest.java",
    ],
    data = [
        "//src/test/unit/resources/util/bson:srcs",
    ],
    tags = ["unit"],
    deps = [
        "//src/main/java/com/xgen/mongot/util",
        "//src/main/java/com/xgen/mongot/util/bson",
        "//src/main/java/com/xgen/mongot/util/bson/parser",
        "//src/main/java/com/xgen/testing",
        "//src/main/java/com/xgen/testing/util",
        "//src/proto/bson:types_java_proto",
        "@com_google_protobuf//:protobuf_java",
        "@maven//:com_google_errorprone_error_prone_annotations",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
        "@maven//:org_apache_commons_commons_lang3",
        "@maven//:org_apache_lucene_lucene_core",
        "@maven//:org_mongodb_bson",
    ],
)
