load("//bazel/java:test.bzl", "java_test_suite")

java_test_suite(
    name = "directory",
    srcs = [
        "ByteReadCollectorTest.java",
        "FileSystemDirectoryTest.java",
    ],
    tags = ["unit"],
    deps = [
        "//src/main/java/com/xgen/mongot/index/lucene/directory",
        "//src/main/java/com/xgen/mongot/metrics",
        "@maven//:io_micrometer_micrometer_core",
        "@maven//:junit_junit",
        "@maven//:org_apache_lucene_lucene_core",
        "@maven//:org_mockito_mockito_core",
    ],
)
