load("//bazel/java:package.bzl", "java_library")

java_library(
    name = "functionalinterfaces",
    srcs = [
        "CheckedBiConsumer.java",
        "CheckedBiExceptionFunction.java",
        "CheckedBiFunction.java",
        "CheckedBinaryOperator.java",
        "CheckedConsumer.java",
        "CheckedFunction.java",
        "CheckedRunnable.java",
        "CheckedSupplier.java",
        "CheckedSupplier2.java",
    ],
    visibility = ["//visibility:public"],
)
