filegroup(
    name = "embedding-service-configs",
    srcs = ["embedding-service-configs.yml"],
    visibility = [
        "//src/main/java/com/xgen/mongot/config/provider/community/embedding:__pkg__",
        "//src/test/unit/java/com/xgen/mongot/config/provider/community:__pkg__",
        "//src/test/unit/java/com/xgen/mongot/config/provider/community/embedding:__pkg__",
    ],
)
