load("//bazel/java:package.bzl", "java_library")

java_library(
    name = "counts",
    testonly = True,
    srcs = ["CountBuilder.java"],
    visibility = ["//visibility:public"],
    exports = ["//src/main/java/com/xgen/mongot/index/query/counts"],
    deps = ["//src/main/java/com/xgen/mongot/index/query/counts"],
)
