load("//bazel/java:package.bzl", "java_library")

java_library(
    name = "blobstore",
    srcs = [
        "BlobstoreException.java",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//src/main/java/com/xgen/mongot/util",
    ],
)
