load("//bazel/java:package.bzl", "java_library")

java_library(
    name = "attributes",
    srcs = [
        "TokenStreamTransformationStage.java",
        "TokenStreamType.java",
        "TokenStreamTypeAware.java",
    ],
    visibility = ["//visibility:public"],
)
