load("//bazel/java:package.bzl", "java_library")

java_library(
    name = "type",
    srcs = [
        "NonNullValueType.java",
        "ValueType.java",
    ],
    visibility = ["//visibility:public"],
)
