load("//bazel/java:package.bzl", "java_library")

java_library(
    name = "exceptions",
    srcs = [
        "EmbeddingProviderBatchingException.java",
        "EmbeddingProviderNonTransientException.java",
        "EmbeddingProviderTransientException.java",
        "MaterializedViewNonTransientException.java",
        "MaterializedViewTransientException.java",
    ],
    visibility = ["//:__subpackages__"],
)
