package com.xgen.mongot.util;

import org.junit.Assert;
import org.junit.Test;

public class RuntimeTest {
  @Test
  public void testRuntimeThreadDump() {
    var threadDump = Runtime.INSTANCE.getThreadDump();
    // `getThreadDump` must be a part of the stack trace generated by getThreadDump
    Assert.assertTrue(threadDump.contains("getThreadDump"));
  }
}
