load("//bazel/java:test.bzl", "mongot_java_unit_test_suite")

mongot_java_unit_test_suite(
    name = "lib",
    deps = [
        "org.apache.lucene:lucene-core",
        "//src/main/java/com/xgen/testing/util",
    ],
)
