load("//bazel/java:package.bzl", "java_library")

java_library(
    name = "config",
    srcs = ["MaterializedViewCollectionMetadata.java"],
    visibility = ["//visibility:public"],
    deps = ["//src/main/java/com/xgen/mongot/util"],
)
