load("//bazel/java:test.bzl", "mongot_java_unit_test_suite")

mongot_java_unit_test_suite(
    name = "lib",
    resources = True,
    test_module = "testing",
    deps = [
        "//src/main/java/com/xgen/testing",
    ],
)
