load("//bazel/java:package.bzl", "java_library")

java_library(
    name = "auth",
    srcs = [
        "SecurityConfig.java",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//src/main/java/com/xgen/mongot/config/util",
        "//src/main/java/com/xgen/mongot/util",
        "//src/main/java/com/xgen/mongot/util/mongodb",
    ],
)
