load("@rules_java//java:defs.bzl", "java_test")

# gazelle:ignore

java_test(
    name = "UnsafeCollectorsCheckerTest",
    srcs = ["UnsafeCollectorsCheckerTest.java"],
    tags = ["unit"],
    deps = [
        "@maven//:junit_junit",
    ],
)
