/**
 * Generates realistic US Addresses. This produces probabilistically unique addresses (trillions of
 * combinations). Modest effort is invested in keeping distribution of some terms inline with real
 * world data.
 */
class AddressGenerator {

  static mod(n, m) {
    return (0x7F_FF_FF_FF & n) % m;
  }

  static get() {
    const cityState = AddressGenerator.getCityAndState()

    // Each (city,state) defines its own street number length. Based on sample from NAD
    const numberFormat = AddressGenerator.mod(AddressGenerator.hashStr(cityState), 97);
    let streetNum = 0
    if (numberFormat < 10) {
      streetNum = Mongot.nextInt(10, 100)
    } else if (numberFormat < 40) {
      streetNum = Mongot.nextInt(100, 1_000)
    } else if (numberFormat < 90) {
      streetNum = Mongot.nextInt(1000, 10_000)
    } else {
      streetNum = Mongot.nextInt(10_000, 50_000)
    }

    let address = streetNum
        + " " + Mongot.choose(AddressGenerator.streets)
        + " " + AddressGenerator.sampleStreetType()

    // Hash addresses to consistently treat them as an apartment complex
    // Ignore city/state info for this, otherwise apartment complexes would always have size=1
    if (AddressGenerator.mod(AddressGenerator.hashStr(address),  16) === 0) {
      address += " apt " + Mongot.nextInt(100, 200);
    }
    return address + " " + cityState;
  }

  static hashStr(s) {
    let h = 0;
    for (let i = 0; i < s.length; i++) {
      h = Math.imul(31, h) + s.charCodeAt(i) | 0;
    }
    return h;
  }

  static sampleStreetType() {
    // Sample street suffix with weight proportional to its array index
    const n = AddressGenerator.suffix.length
    const maxTriangleArea = (n * n) / 2.0
    const area = Math.random() * maxTriangleArea
    const minTriangleLengthWithArea = Math.trunc(Math.sqrt(2 * area))

    // 12.9% of real street names contain a cardinal direction
    if (Mongot.randInt(8) === 0) {
      return AddressGenerator.suffix[minTriangleLengthWithArea]
          + " " + Mongot.choose(["North", "South", "East", "West"])
    }
    return AddressGenerator.suffix[minTriangleLengthWithArea]
  }

  static getCityAndState() {
    // Use one random to determine (city, state) pair. Cities appear in multiple states but not
    // all combinations are possible.
    const avgCitiesPerState = 40
    const rand = Mongot.randInt(AddressGenerator.states.length * avgCitiesPerState);
    const stateIndex = rand % AddressGenerator.states.length;
    const cityIndex = ((rand << 16) ^ rand) % AddressGenerator.cities.length;

    return AddressGenerator.cities[cityIndex] + ", " + AddressGenerator.states[stateIndex];
  }

  // cities.length needs to be prime for uniform distribution among states
  static cities = [
    "La Quinta",
    "Carbon Hill",
    "Rowley",
    "Portola",
    "Wawarsing",
    "West Lynchburg",
    "Rural Hill",
    "Vernal",
    "Yukon",
    "Jordan",
    "Meggett",
    "Willmar",
    "Wilton Manors",
    "Skyline Acres",
    "Keyport",
    "Northbridge",
    "Duchesne",
    "Elizabethton",
    "Cheshire",
    "Ahwatukee Foothills",
    "Delhi",
    "Radford",
    "San Anselmo",
    "Holiday Island",
    "Walworth",
    "White City",
    "Manson",
    "West Rancho Dominguez",
    "Gloucester",
    "Morgan",
    "Selinsgrove",
    "Tiffin",
    "Helena Valley Southeast",
    "Fort Benton",
    "Uxbridge",
    "Mona",
    "Latham",
    "Holden",
    "Spanish Springs",
    "Springhill",
    "Hackberry",
    "Guin",
    "Manheim",
    "Agawam",
    "Salmon Brook",
    "Woodinville",
    "West York",
    "Hidden Spring",
    "Nesquehoning",
    "Mohawk",
    "Garner",
    "Ashburn",
    "Calera",
    "Frankton",
    "Saint Augusta",
    "Beatty",
    "Lake Butler",
    "Broward Estates",
    "Yorklyn",
    "Flower Hill",
    "West Bloomfield Township",
    "Angel Fire",
    "Houston",
    "Baytown",
    "Franklin Lakes",
    "Northwest Harborcreek",
    "Versailles",
    "Eastgate",
    "New Chicago",
    "Homer City",
    "Tiger Point",
    "Grayslake",
    "Paramount-Long Meadow",
    "Deansboro",
    "Juneau",
    "Center Hill",
    "Winnsboro Mills",
    "Old River-Winfree",
    "Peaceful Valley",
    "Navassa",
    "Whiskey Creek",
    "Lauderdale",
    "West Scarborough",
    "Hauppauge",
    "Lorena",
    "Morongo Valley",
    "Everett",
    "Harris",
    "Saint Gabriel",
    "Kendall West",
    "Hoxie",
    "Cypress Gardens",
    "Butler Beach",
    "Sanborn",
    "Ford Heights",
    "Terrebonne",
    "Hueytown"
  ]

  static states = [
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming"
  ]

  // Ranked from least to most common
  static suffix = [
    "Terrace",
    "View",
    "Path",
    "Trail",
    "Boulevard",
    "Place",
    "Circle",
    "Way",
    "Avenue",
    "Street",
    "Lane",
    "Court",
    "Road",
    "Drive",
  ]

  static streets = [
    "10th",
    "11th",
    "12th",
    "13th",
    "14th",
    "15th",
    "16th",
    "17th",
    "18th",
    "19th",
    "20th",
    "21st",
    "22nd",
    "23rd",
    "Aachen",
    "Aaron Creek",
    "Aaron Lloyd",
    "Aaron Square",
    "Aaron",
    "Abbe",
    "Abbermare",
    "Abbeville",
    "Abbey Glen",
    "Abbey Park",
    "Abbey Wood",
    "Abbey",
    "Abbeydale",
    "Abbeywood Village",
    "Abbeywood",
    "Abbie",
    "Abbington",
    "Abborrsford",
    "Abbot Grove",
    "Abbot",
    "Abbotsbury",
    "Abbotsford",
    "Abbott Farm",
    "Abbott Glen",
    "Abbott Grove",
    "Abbott Oaks",
    "Abbott",
    "Abbotts Bridge",
    "Abbotts Glen",
    "Abbotts Mill",
    "Abbotts Oak",
    "Abbotts Pointe",
    "Abbotts Walk",
    "Abbotts",
    "Abby Brook",
    "Abby Chase",
    "Abby Hill",
    "Abby",
    "Abeel",
    "Abel",
    "Abelia",
    "Abercorn",
    "Abercorne",
    "Abercrombie",
    "Aberdale",
    "Aberdare",
    "Aberdeen Bend",
    "Aberdeen Park",
    "Aberdeen",
    "Aberdeens Folly",
    "Aberleigh",
    "Abernathy",
    "Aberrone",
    "Abi",
    "Abigail",
    "Abilene",
    "Abingdon",
    "Abington Hall",
    "Abington Ridge",
    "Abington Woods",
    "Abington",
    "Ablemarle",
    "Abney Highland",
    "Abney Point",
    "Abney",
    "Abraham Freed",
    "Abraham",
    "Abrahamson",
    "Abram",
    "Abrams Mill",
    "Abrams",
    "Abrum",
    "Abundance",
    "Acacia",
    "Acadamy",
    "Academia",
    "Academy Hill Green",
    "Academy Hill",
    "Academy Knolls",
    "Academy",
    "Acadia",
    "Acadian",
    "Acapulco",
    "Access",
    "Accolon",
    "Accomac",
    "Ace",
    "Acer",
    "Achcom",
    "Achille",
    "Achilles",
    "Ackerman",
    "Ackermans",
    "Ackley",
    "Ackman",
    "Acme",
    "Acorn Hill Hollow",
    "Acorn Hill",
    "Acorn Woods",
    "Acorn",
    "Acres",
    "Acron",
    "Acrux",
    "Acton",
    "Acushnet",
    "Ada",
    "Adair",
    "Adaire",
    "Adam",
    "Adams Court Noirth",
    "Adams Farm",
    "Adams Gardens",
    "Adams Hill",
    "Adams Lake",
    "Adams Mill",
    "Adams Park",
    "Adams Point",
    "Adams",
    "Adamson",
    "Adare",
    "Adbin Lea",
    "Addington",
    "Addis",
    "Addison Pond",
    "Addison",
    "Addition",
    "Addlestone",
    "Addy",
    "Adee",
    "Adelaide",
    "Adelante",
    "Adele",
    "Adeline",
    "Adell",
    "Adena Brook",
    "Adena Trace",
    "Adena",
    "Adenas Walk",
    "Adirondack",
    "Adirondak",
    "Adkins",
    "Adler",
    "Adloff",
    "Admas",
    "Admiral",
    "Admirals Point",
    "Admirals Walk",
    "Admirals",
    "Admiralton",
    "Adner",
    "Adobe Falls",
    "Adobe",
    "Adonida",
    "Adrian",
    "Adrianna",
    "Adriel",
    "Adrienne",
    "Adsit",
    "Advantis",
    "Adventure Pass",
    "Aegean",
    "Aemilian",
    "Aerial",
    "Aero",
    "Aeronaut",
    "Aeropostale",
    "Aetna",
    "Affirmed",
    "Affleck",
    "Afterglow Vale",
    "Afterglow",
    "Afton",
    "Aftons",
    "Agape",
    "Agarwal",
    "Agassiz",
    "Agate",
    "Agawam",
    "Agena",
    "Agincourt",
    "Agio",
    "Agnes",
    "Agnew",
    "Ahaluna",
    "Aidenn Lair",
    "Aiken Farm",
    "Aiken",
    "Aikens",
    "Ailanthus",
    "Aileen",
    "Ainsley",
    "Ainslie",
    "Ainsworth",
    "Aintree Chase",
    "Aintree Walk",
    "Aintree",
    "Airacobra",
    "Airdale",
    "Airdrie",
    "Airfield",
    "Airline",
    "Airport",
    "Airview",
    "Airway",
    "Airy",
    "Aisha",
    "Aishlins",
    "Akers",
    "Akerswood Cove",
    "Akerswood",
    "Akron",
    "Al",
    "Alabama",
    "Alabaster Cove",
    "Alachua",
    "Aladdin",
    "Alahmar",
    "Alamance",
    "Alamanni",
    "Alameda",
    "Alamingo",
    "Alamo",
    "Alamosa",
    "Alan",
    "Alana",
    "Alans",
    "Alanson",
    "Alanya",
    "Alaska",
    "Alayssa",
    "Alba",
    "Albans",
    "Albany Hill",
    "Albany Post",
    "Albany",
    "Albatross",
    "Albedo",
    "Arkansas",
    "Bush",
    "California",
    "Canada",
    "Cleveland",
    "Colorado",
    "Courtenay",
    "Courtfield",
    "Courthouse Square",
    "Courthouse",
    "Courtland Hill",
    "Courtland",
    "Courtlandt",
    "Courtney Cove",
    "Courtney Mill",
    "Courtney",
    "Courtshire",
    "Courtside",
    "Courtyard",
    "Couse",
    "Cousin Lucys",
    "Cove Lake",
    "Cove Pointe",
    "Cove",
    "Covehill",
    "Covenant",
    "Covenger",
    "Covent Garden",
    "Coventry Commons",
    "Coventry Greene",
    "Coventry Greens",
    "Coventry Pointe",
    "Coventry Square",
    "Coventry Tee",
    "Coventry",
    "Coventryville",
    "Coverdale",
    "Covered Bridge Path",
    "Covered Bridge",
    "Coveridge",
    "Coverly",
    "Covert",
    "Coveside",
    "Covey Chase",
    "Covey Rise",
    "Covey",
    "Coveyrun",
    "Covingron",
    "Covington",
    "Cow Hill",
    "Cowan",
    "Cowardin",
    "Cowbell",
    "Cowboy",
    "Cowcross",
    "Cowdry",
    "Cowell",
    "Cowing",
    "Cowles",
    "Cowling",
    "Cowpath",
    "Cowpens",
    "Cowper",
    "Cox Farm",
    "Cox",
    "Coy",
    "Coyle",
    "Coyote",
    "Cozy",
    "Crab Apple Hill",
    "Crab Apple",
    "Crab Orchard",
    "Crabapple Trace",
    "Crabapple",
    "Crabb",
    "Crabbs",
    "Crabtree Pass",
    "Crabtree Turn",
    "Crabtree",
    "Crackling Branch",
    "Craddock",
    "Cradel Rock",
    "Craford",
    "Craft",
    "Crafton",
    "Crafts",
    "Craftsman",
    "Craftwood",
    "Cragin",
    "Cragmoor",
    "Dakota",
    "Eisenhower",
    "Elm",
    "Filmore",
    "Fleur",
    "Florida",
    "Flower",
    "Forest Ridge",
    "Forest Run",
    "Forest School",
    "Forest Spring",
    "Forest Willow",
    "Forest Woods",
    "Forestbrook",
    "Forestbrooke",
    "Forestdale",
    "Forestgate",
    "Forestglen",
    "Forestview",
    "Forestville",
    "Forestwood",
    "Forge Hill",
    "Forge Mill",
    "Forge",
    "Forgedale",
    "Forklanding",
    "Formby",
    "Forrest Hill",
    "Forrest Hills",
    "Forrest Place",
    "Forrest",
    "Forrester",
    "Forry",
    "Forsgate",
    "Forston",
    "Forsyth",
    "Forsythe",
    "Forsythia",
    "Fort Bedford",
    "Fort Beech",
    "Fort Bevon",
    "Fort Duquesne",
    "Fort Harrods",
    "Fort Hill",
    "Fort Lauderdale",
    "Fort Loudon",
    "Fort Rachel",
    "Fort Sumpter",
    "Fort Totten",
    "Fort Williams",
    "Fort Worth",
    "Fort",
    "Forten",
    "Fortinbras",
    "Fortingale",
    "Fortner",
    "Fortress",
    "Forts Ferry",
    "Fortune",
    "Forty Foot",
    "Forum",
    "Fosdick",
    "Foster",
    "Fostertown",
    "Fostoria",
    "Fothergill",
    "Fotheringham",
    "Foulet",
    "Foulk Woods",
    "Foulke",
    "Foulkrod",
    "Founders Mill",
    "Founders",
    "Foundry",
    "Fount",
    "Fountain Farm",
    "Fountain Hall",
    "Fountain Park",
    "Fountain",
    "Fountainbrook",
    "Fountainhead",
    "Fountayne",
    "Four Leaf",
    "Four Mile",
    "Four Seasons",
    "Four Streams",
    "Four Winds",
    "Four-in-Hand",
    "Foushee",
    "Fowler",
    "Fox Bend",
    "Fox Brook",
    "Fox Brush",
    "Fox Chapel",
    "Fox Chase Point",
    "Fox Cove",
    "Fox Cub Hollow",
    "Fox Dale",
    "Fox Den",
    "Fox Dog",
    "Fox Fire",
    "Fox Glen",
    "Fox Glenn",
    "Fox Glove",
    "Fox Grape",
    "Fox Haven",
    "Fox Hill",
    "Fox Hills",
    "Fox Hollow",
    "Fox Hound Chase",
    "Fox Hound",
    "Fox Hunt",
    "Fox Hunter",
    "Fox Hunters",
    "Fox Lair",
    "Fox Meade",
    "Fox Meadow",
    "Fox Meadows",
    "Fox Mill Run",
    "Fox Mill",
    "Fox Moore",
    "Fox Path",
    "Fox Point",
    "Fox Pointe",
    "Fox Ridge",
    "Fox Run",
    "Fox Sedge",
    "Fox Sparrow",
    "Fox Terrier",
    "Fox Trail",
    "Fox Trap",
    "Fox Tree",
    "Fox Trot",
    "Fox Valley",
    "Fox Walk",
    "Fox",
    "Foxboro",
    "Foxborough",
    "Foxbrook",
    "Foxbury",
    "Foxchase",
    "Foxclove",
    "Foxcroft",
    "Foxcross",
    "Foxdale",
    "Foxe Basin",
    "Foxfern",
    "Foxfield",
    "Foxfields",
    "Foxfire",
    "Foxford",
    "Foxgate",
    "Foxgayte",
    "Foxglove",
    "Foxhall",
    "Foxhill",
    "Foxhunt",
    "Foxlair",
    "Foxmask",
    "Foxmeadow",
    "Foxmoor",
    "Foxon",
    "Foxridge",
    "Foxshire",
    "Foxtail",
    "Foxton",
    "Foxview",
    "Foxwick",
    "Foxwood",
    "Foxx",
    "Fradswell",
    "Fragrant Lillies",
    "Fran Mar",
    "France",
    "Frances Green",
    "Frances",
    "Francesca",
    "Francher",
    "Francis Lee",
    "Francis Lewis",
    "Francis Meyers",
    "Francis",
    "Franck",
    "Franco",
    "Frandor",
    "Franekn",
    "Frank",
    "Frankel",
    "Franklin Farms",
    "Franklin Hills",
    "Franklin Meadows",
    "Franklin Mills",
    "Franklin",
    "Franklyn",
    "Franks",
    "Frans",
    "Fraser",
    "Frassetto",
    "Frawley",
    "Frazer",
    "Frazier",
    "Freas",
    "Freasland",
    "Freca",
    "Frechette",
    "Fred",
    "Freda",
    "Fredella",
    "Fredendall",
    "Frederic",
    "Frederick Douglas",
    "Frederick",
    "Fredericks",
    "Fredericksburg",
    "Fredonia",
    "Fredrick",
    "Freds",
    "Freedom Valley",
    "Freedom",
    "Freedoms",
    "Freedon",
    "Freeland",
    "Freeman",
    "Freemans",
    "Freese",
    "Freetown",
    "Freier",
    "Fremont",
    "Gait",
    "Galacia",
    "Galahad",
    "Galan",
    "Galax",
    "Galaxy",
    "Galberry",
    "Galdi",
    "Gale Rowe",
    "Gale",
    "Galean",
    "Galehouse",
    "Galen",
    "Galena",
    "Galer",
    "Gales",
    "Galewind",
    "Galicia",
    "Galie",
    "Galies Pointe",
    "Galileo",
    "Galiot",
    "Gallagher",
    "Gallahadion",
    "Gallant Fox",
    "Gallant",
    "Gallatin",
    "Gallery",
    "Gallo",
    "Gallop",
    "Galloping Brook",
    "Galloping",
    "Gallow",
    "Gallows Hill",
    "Gallows",
    "Gallup",
    "Galston",
    "Galt",
    "Galton",
    "Galveston",
    "Galvin",
    "Gamay",
    "Gambel",
    "Gamble",
    "Gambocz",
    "Gambrel",
    "Game Farm",
    "Gamesford",
    "Gamewell",
    "Gamewood",
    "Gamma",
    "Gander",
    "Gannet",
    "Gannon",
    "Gansevoort",
    "Ganton",
    "Gantt",
    "Gaping Rock",
    "Garapan",
    "Garber",
    "Garcia",
    "Garden Hill",
    "Garden Oaks",
    "Garden Park",
    "Garden Ridge",
    "Garden Spring",
    "Garden State",
    "Garden Trace",
    "Garden Wall",
    "Garden",
    "Gardenbrook",
    "Gardengate",
    "Gardenia",
    "Garfield",
    "Georgia",
    "Grant",
    "Harrison",
    "Hayes",
    "Hoover",
    "Idaho",
    "Jackson",
    "Jefferson",
    "Johnson",
    "Kansas",
    "Kentucky",
    "Lakota",
    "Lincoln",
    "Madison",
    "Main",
    "Maine",
    "Maple",
    "Maryland",
    "McKinley",
    "Mexico",
    "Monroe",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Mexico",
    "New York",
    "Oak",
    "Obama",
    "Ohio",
    "Oregon",
    "Pierce",
    "Polk",
    "Quincy",
    "Tennessee",
    "Texas",
    "Tyler",
    "Utah",
    "Van Buren",
    "Vermont",
    "Virginia",
    "Washington",
    "Wisconsin",
    "Wolf",
  ]
}
